services:
  indexer:
    build:
      context: ./Indexer_1
      dockerfile: DockerfileIndexer
    image: searchoracle/indexer_one_file
    container_name: indexer
    volumes:
      - datalake:/app/datalake/
      - datamart:/app/datamart/
    environment:
      - DATALAKE_PATH=/app/datalake/
      - DATAMART_PATH=/app/datamart/

  crawler:
    build:
      context: ./Crawler
      dockerfile: DockerFileCrawler
    image: searchoracle/crawler
    container_name: crawler
    depends_on:
      - indexer
    volumes:
      - datalake:/app/datalake/
    environment:
      - JAVA_OPTS=-Xmx512m

  query_engine:
    build:
      context: ./Query_Engine
      dockerfile: DockerfileQueryEngine
    image: searchoracle/query_engine_one_file
    container_name: query_engine
    depends_on:
      - crawler
    volumes:
      - datalake:/app/datalake/
      - datamart:/app/datamart/
    environment:
      - DATALAKE_PATH=/app/datalake/
      - DATAMART_PATH=/app/datamart/
    ports:
      - "8080:8080"

  user_interface:
    build:
      context: ./User_Interface
      dockerfile: DockerfileUserInterface
    image: searchoracle/user_interface
    container_name: user_interface
    depends_on:
      - query_engine
    ports:
      - "3000:80"


volumes:
  datalake:
  datamart: